### ISSUE TITLE
Fix broken links to README

### ISSUE THREAD

**Issue by CharlieZhao95** [chenzomi12/DeepLearningSystem#5]
This issue is used to record some potential incorrect links. 😃

**Comment by CharlieZhao95** [comment]
Change `| 自动微分 | 04 三种实现方法        | [silde](./04.grad_mode.pdf)` to `| 自动微分 | 04 三种实现方法           | [silde](./04.implement.pdf)`.

**Comment by chenzomi12** [comment]
The PR is merged, close these issues. Great Job!
