### ISSUE TITLE
张量自动并行的 pdf & ppt 应该是搞错了，和前一节张量并行材料一模一样。

### ISSUE THREAD

**Issue by popomen** [chenzomi12/DeepLearningSystem#55]
![image](https://github.com/chenzomi12/DeepLearningSystem/assets/59364722/23281837-1335-40e5-be42-98bfc5c234f1)

Frontend/06_Parallel/03.tensor_parallel.pdf
Frontend/06_Parallel/04.mindspore_parallel.pdf

张量自动并行的 pdf & ppt 应该是搞错了，和前一节张量并行材料一模一样。

**Comment by chenzomi12** [comment]
发现得很好，感谢提醒，目前已经修复提交PR。
