### ISSUE TITLE
Add some learning resources

### ISSUE THREAD

**Issue by pandalee99** [chenzomi12/DeepLearningSystem#57]
我学校开过《智能计算系统》这门课，有一些视频链接和实验笔记以及其他资源，我可以放上来吗，额外放一个文件夹收集

**Comment by chenzomi12** [comment]
非常感谢您的贡献！

视频链接，你可以放在对应大章节的inference，作为学习参考。
实验笔记可以在对应的章节放一个experience的目录，方便他人学习。

**Comment by pandalee99** [comment]
thanks
