### ISSUE TITLE
表格内容错误：与上一章表格内容重复

### ISSUE THREAD

**Issue by MrArcrM** [chenzomi12/DeepLearningSystem#58]
表格内容错误：与上一章表格内容重复

https://github.com/chenzomi12/DeepLearningSystem/blob/40808fd83aa57b5c2fa032b9efc82b14b5098cc3/025FW_AIAlgo/README.md?plain=1#L15

**Comment by chenzomi12** [comment]
嗯嗯，感谢提醒，后面写文章写到这里会改的。
