### ISSUE TITLE
希望加入

### ISSUE THREAD

**Issue by ShenghangZhang** [chenzomi12/DeepLearningSystem#61]
这个开源项目做的非常不错，随着LLM大火，也需要了解学习AIsys相关内容，才能完成企业内AI落地，因此希望加入开源项目一起学习讨论

**Comment by chenzomi12** [comment]
好呀，你看看能够贡献那部分？是讲课，还是帮忙写文档？看怎么加你联系方式

**Comment by ShenghangZhang** [comment]
联系您gmail了[chenzomi12@gmail.com]
