### ISSUE TITLE
希望加入~

### ISSUE THREAD

**Issue by XcodeHw** [chenzomi12/DeepLearningSystem#62]
一直也有学习ai编译器的想法，就是希望有类似的项目可以参与，虽然我是新手，但也想尽份力，我目前是从事深度学习工作的，不知道可以做点什么

**Comment by labspc** [comment]
> 一直也有学习ai编译器的想法，就是希望有类似的项目可以参与，虽然我是新手，但也想尽份力，我目前是从事深度学习工作的，不知道可以做点什么

hahah我也是，这两天在看编译器有关的文章，从b站找到了这里。但是，我目前不懂c++不知道能不能做dl方面的工作。

**Comment by XcodeHw** [comment]
再想的多一点，我们能不能参与做一个开源的AI编译器~虽然感觉挺难的，哈哈

**Comment by chenzomi12** [comment]
你有什么好的想法吗？

**Comment by XcodeHw** [comment]
> 你有什么好的想法吗？

想法就是能有个循序渐进的教程，学完掌握一些知识的时候，可以简单的开发一个小型ai编译器。
主要没发现有专门教ai编译器的教程，如果能一起做，应该对想学习或者想入门的同学有帮助吧

**Comment by ytzhao** [comment]
统一楼上的，我觉得 @chenzomi12  zomi讲的非常的深入浅出，特别适合来弥补一些理论知识，但是在实际动手上，还有点点不足，如果大家都有想法的，可以尝试一起开发，共同学习共同进步 ;-)

**Comment by chenzomi12** [comment]
大家可以一起开发，提供一些实际的案例过俩。
