### ISSUE TITLE
建议在《分布式并行》里面增加“ZeRO优化器”

### ISSUE THREAD

**Issue by shifang99** [chenzomi12/DeepLearningSystem#64]
Megatron-LM支持：数据并行+张量并行+流水并行。
DeepSpedd支持：数据并行+ZeRO优化器。
Megatron-DeepSpeed支持：数据并行+张量并行+流水并行+ZeRO优化器。
ZeRO优化器分为三种：ZeRO-stage1、ZeRO-stage1、ZeRO-stage3。
其中ZeRO-stage3也被称作FSDP。

ZeRO或者FSDP的应用示例：
1. https://github.com/tatsu-lab/stanford_alpaca
2. https://github.com/lm-sys/FastChat
3. https://github.com/hiyouga/LLaMA-Efficient-Tuning/blob/main/README_zh.md

ZeRO相关参考资料：
1. Samyam Rajbhandari, Jeff Rasley, Olatunji Ruwase, Yuxiong He. (2019) ZeRO: memory optimizations toward training trillion parameter models. [arXiv:1910.02054](https://arxiv.org/abs/1910.02054) and [In Proceedings of the International Conference for High Performance Computing, Networking, Storage and Analysis (SC ‘20)](https://dl.acm.org/doi/10.5555/3433701.3433727).
2.  ZeRO++: A leap in speed for LLM and chat model training with 4X less communication](https://www.microsoft.com/en-us/research/blog/deepspeed-zero-a-leap-in-speed-for-llm-and-chat-model-training-with-4x-less-communication/)
3. [FairScale](https://github.com/facebookresearch/fairscale) FULLY SHARDED DATA PARALLEL  DOC https://fairscale.readthedocs.io/en/stable/api/nn/fsdp.html

**Comment by chenzomi12** [comment]
太赞了，你可以贡献ppt或者对应内容吗？我跟你一起制作一期

**Comment by zhenzhen2017** [comment]
好的，很高兴合作。

**Comment by shifang99** [comment]
zomi，你好。
刚刚发现你之前的这个视频在10分26秒左右已经讲过ZeRO优化器了。
PyTorch数据并行怎么实现？DP、DDP、FSDP数据并行原理？【分布式并行】系列第02篇
https://www.bilibili.com/video/BV1JK411S7gL/?spm_id_from=333.999.0.0&vd_source=9b3db7b3617dd006dddc6c32d542a84a

DeepSpeed提出的ZeRO优化器包括ZeRO-DP和ZeRO-R，其中ZeRO-DP有不同的Stage。
pytorch中的FSDP 对应DeepSpeed中的ZeRO-DP的其中一个stage。
