### ISSUE TITLE
资料（pdf，pptx）无法打开和下载

### ISSUE THREAD

**Issue by liaoqw94** [chenzomi12/DeepLearningSystem#65]
点开课程列表，选择任意一条.pdf文件点击进去，显示
Error rendering embedded code

Invalid PD
![image](https://github.com/chenzomi12/DeepLearningSystem/assets/145897434/58876269-7578-401d-8060-e6db33267d38)

请问怎么解决，是我环境的问题吗？
谢谢作者

**Comment by chenzomi12** [comment]
你的环境问题，直接git下来自己本地打开好了。
