### ISSUE TITLE
希望优化一下自动微分部分

### ISSUE THREAD

**Issue by zjzjwang** [chenzomi12/DeepLearningSystem#66]
我在b站看到您关于AI芯片的介绍从而发现了这个repo，非常感谢您能够开源这些优秀的资料。
结合我之前学习的资料，希望能对自动微分部分进行一些修改，或者添加一个新的章节。

新的章节主要结合代码实现进行讲解，从基本的支持自动求导的Value类开始，最终实现一个MLP网络的训练，总代码量大概200行不到。

如果您觉得合适的话，我们可以讨论一下怎么修改。

修改主要参考：
1.  [Andrej Karpathy](https://karpathy.ai/) 的 [youtube 视频](https://www.youtube.com/watch?v=VMj-3S1tku0)  
2.  [github repo](https://github.com/karpathy/micrograd) 
3.  [jupyter notebook](https://github.com/karpathy/nn-zero-to-hero/blob/master/lectures/micrograd/micrograd_lecture_second_half_roughly.ipynb)

另外文档中还有一些笔误，我看到的话也可以提交修改。
目前我正在学习cuda和ai编译相关的内容，如果有机会的话也可以看看有没有合适的内容可以贡献。

**Comment by chenzomi12** [comment]
非常赞！你后面提交的代码，可以#issues id就可以关联这个issues了
