### ISSUE TITLE
最后的inference是不是搞错了？是reference吧？

### ISSUE THREAD

**Issue by sleepwalker2017** [chenzomi12/DeepLearningSystem#7]
[DeepLearningSystem](https://github.com/chenzomi12/DeepLearningSystem)/[Compiler](https://github.com/chenzomi12/DeepLearningSystem/tree/main/Compiler)/[Backend](https://github.com/chenzomi12/DeepLearningSystem/tree/main/Compiler/Backend)/06.auto_tuning.pdf

**Comment by chenzomi12** [comment]
是的是的，写错了哈！欢迎您提交一个PR，然后合入开源社区，在github上面留下你的修改哈！
