### ISSUE TITLE
在应用层与编程语言之间补充一层训练框架/平台比如nvidia Megatron LLM  、百度飞浆平台

### ISSUE THREAD

**Issue by SchopenhauerZhang** [chenzomi12/DeepLearningSystem#77]
like this：

APP:  NLP something else

FRAME： nvidia Megatron LLM、 baidu PaddlePaddle and something else 

language： Python

**Comment by chenzomi12** [comment]
还真的不是这样放，这几层不是这么放的哈。看大模型那章节，有大模型的分层架构介绍
