### ISSUE TITLE
zomi有考虑配套出一些动手实践的例子没有呢？

### ISSUE THREAD

**Issue by JayHeYang** [chenzomi12/DeepLearningSystem#8]

**Comment by chenzomi12** [comment]
可以出的，不过工作太忙没时间整理，要是有感兴趣的小伙伴一起参与就好了。

**Comment by liguodongiot** [comment]
@JayHeYang 我这里有一些大模型动手时间的例子，配置教程和代码。

https://github.com/liguodongiot/llm-action

@chenzomi12  大佬，看看有没有合适的章节可以放置到DeepLearningSystem。
